name: Run fMRI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # permet de lancer manuellement depuis GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    # Beaucoup de RAM pour le fMRI
    # GitHub Actions gratuit = 7GB RAM, 14GB storage
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          invoke run

      - name: Upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-outputs
          path: outputs/
